name: Publish Docker image and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0  # Updated version for stability
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.0  # Updated version for features
        with:
          # Assuming your image has the format vivekmishra1712/pakhi:<tag>
          images: vivekmishra1712/pakhi:latest  # Replace with your image name and tag pattern

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.2  # Updated version for features
        with:
          context: .  # Build context is the current directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_to_gKE:  # Corrected case for Kubernetes Engine
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated for consistency

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker CLI
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          gcloud auth configure-docker

      - name: Deploy Helm chart to GKE
        # Corrected path and namespace placeholders
        run: |
          helm upgrade --install myapp ./helm/helloWeb3 \
            --namespace your-namespace \
            --set image=vivekmishra1712/pakhi:latest  # Assuming the image from previous job
            --kubeconfig=${{ secrets.GKE_KUBECONFIG_PATH }}  # Use secret for kubeconfig
